#!/usr/bin/env bash
set -eo pipefail

export PATH="$HOME/homebrew/bin:$HOME/.local/bin:$HOME/homebrew/opt/node/bin:/usr/local/bin:/usr/bin:/bin"
AGENT_HOME="$HOME/.paperclip/instances/default/workspaces/e7a1b2c3-d4e5-f6a7-b8c9-0d1e2f3a4b5c"
INBOX="$AGENT_HOME/inbox"
OUTBOX="$AGENT_HOME/outbox"
SCRIPTS="$HOME/.claude/skills/zuma-spg-recap-agent"
REQUEST_FILE="$INBOX/spg_request.json"

export PGHOST="76.13.194.120"
export PGPORT="5432"
export PGDATABASE="openclaw_ops"
export PGUSER="openclaw_app"
export PGPASSWORD='Zuma-0psCl4w-2026!'

log() { echo "[spg-hb $(date +%H:%M:%S)] $*"; }

send_wa_single() {
  local PHONE="$1" MSG="$2"
  local OK
  OK=$(openclaw message send --channel whatsapp --target "$PHONE" --message "$MSG" --json 2>/dev/null | grep -c '"ok"' || true)
  if [ "$OK" -lt 1 ]; then
    log "WA send failed to $PHONE, restarting gateway..."
    openclaw gateway restart 2>/dev/null || true
    sleep 5
    openclaw message send --channel whatsapp --target "$PHONE" --message "$MSG" --json 2>/dev/null || log "WA retry failed"
  fi
}

send_wa() {
  local MSG="$1"
  if [ -n "$REQ_PHONE" ] && [ "$REQ_PHONE" != "+628983539659" ]; then
    send_wa_single "$REQ_PHONE" "$MSG"
  fi
  send_wa_single "+628983539659" "$MSG"
}

upload_gsheet() {
  python3 "$HOME/.claude/skills/zuma-plano-ro-skills/step3-zuma-ro-surplus-skills/upload_gsheet.py" \
    --file "$1" --folder "$2" 2>&1 | tail -1 | sed 's/GSHEET_LINK=//'
}

if [ ! -f "$REQUEST_FILE" ]; then
  log "No request file. Nothing to do."
  exit 0
fi

log "Reading request..."
AREA=$(python3 -c "import json; print(json.load(open('$REQUEST_FILE')).get('area','ALL'))")
MONTH=$(python3 -c "import json; print(json.load(open('$REQUEST_FILE')).get('month','$(date +%-m)'))")
YEAR=$(python3 -c "import json; print(json.load(open('$REQUEST_FILE')).get('year','$(date +%Y)'))")
REQ_PHONE=$(python3 -c "import json; print(json.load(open('$REQUEST_FILE')).get('requester_phone',''))")
REQ_NAME=$(python3 -c "import json; print(json.load(open('$REQUEST_FILE')).get('requester_name',''))")

log "Area=$AREA Month=$MONTH/$YEAR Requester=$REQ_NAME"

OUTFILE="$OUTBOX/SPG-Recap-${YEAR}${MONTH}-${AREA}.xlsx"

python3 "$SCRIPTS/generate_spg_recap.py" \
  --area "$AREA" --month "$MONTH" --year "$YEAR" --output "$OUTFILE" \
  2>&1 | while read -r line; do log "  $line"; done

if [ ! -f "$OUTFILE" ]; then
  log "ERROR: Output not generated"
  send_wa "SPG Recap $AREA $MONTH/$YEAR GAGAL. Hubungi admin."
  mv "$REQUEST_FILE" "$REQUEST_FILE.done.$(date +%s)" 2>/dev/null || true
  exit 1
fi

log "Uploading to GDrive..."
GLINK=$(upload_gsheet "$OUTFILE" "SPG Recap/$YEAR")
log "GSheet: $GLINK"

MONTH_NAMES="Jan Feb Mar Apr Mei Jun Jul Agu Sep Okt Nov Des"
MNAME=$(echo $MONTH_NAMES | cut -d' ' -f"$MONTH")

send_wa "SPG Achievement Recap *${AREA}* — *${MNAME} ${YEAR}* selesai.

Link: $GLINK

Sheets:
- SPG Leaderboard (ranking per SPG, achievement %)
- Double Store (SPG transaksi di >1 toko)

_Generated by SPG-Recap-Agent (Paperclip)_"

mv "$REQUEST_FILE" "$REQUEST_FILE.done.$(date +%s)" 2>/dev/null || true
log "Done."
